---Represents an entry in the Devdocs registery
---@see https://devdocs.io/docs.json
---@class RegisteryEntry
---@field name string
---@field slug string
---@field type string
---@field version number
---@field release string
---@field mtime number
---@field db_size number
---@field links? table<string, string>
---@field attribution string

---Represents an entry in the index.json file
---NOTE: alias is filled at runtime
---@see nvim_devdocs_path/index.json
---@class DocEntry
---@field name string
---@field path string
---@field link string
---@field alias string
